### ISSUE TITLE
error! Error: Max buffer length exceeded: sgmlDecl

### ISSUE THREAD

**Issue by berkes** [sammerry/node-mongosm#24]
Stacktrace:

```
Line: 2511
Column: 258
Char: 
    at error (XXX/lib/node_modules/mongosm/node_modules/sax/lib/sax.js:616:8)
    at checkBufferLength (XXX/lib/node_modules/mongosm/node_modules/sax/lib/sax.js:120:11)
    at SAXParser.write (XXX/lib/node_modules/mongosm/node_modules/sax/lib/sax.js:1312:54)
    at SAXStream.write (XXX/lib/node_modules/mongosm/node_modules/sax/lib/sax.js:202:16)
    at ReadStream.ondata (_stream_readable.js:709:20)
    at ReadStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
```

Sax has its `sax.MAX_BUFFER_LENGTH 64 * 1024`.  It should probably be increased by this consumer as per the comment in Sax:

```
// When we pass the MAX_BUFFER_LENGTH position, start checking for buffer overruns.
// When we check, schedule the next check for MAX_BUFFER_LENGTH - (max(buffer lengths)),
// since that's the earliest that a buffer overrun could occur.  This way, checks are
// as rare as required, but as often as necessary to ensure never crossing this bound.
// Furthermore, buffers are only tested at most once per write(), so passing a very
// large string into write() might have undesirable effects, but this is manageable by
// the caller, so it is assumed to be safe.  Thus, a call to write() may, in the extreme
// edge case, result in creating at most one complete copy of the string passed in.
// Set to Infinity to have unlimited buffers.
```

**Comment by berkes** [comment]
Ugh. 

My mistake. I was passing a `pbf` file to the parser, not a proper OSM XML file.
